repos:
  # Ruff
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.269
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  # Black
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black 
        args: [--line-length=88, --preview]
  # MyPy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        additional_dependencies: [types-tqdm]
        args: [--strict, --show-error-codes]
  